    - name: Routers Configuration
    hosts: device_roles_router
    tasks:
      - name: Set Devices Name
        community.routeros.command:
          commands:
            - /system identity set name="{{interfaces[0].device.name}}"
      - name: Set additional IP
        community.routeros.command:
          commands:
          - /interface bridge add name="{{interfaces[1].display}}"
          - /ip address add address="{{interfaces[1].ip_addresses[0].address}}" interface="{{interfaces[1].display}}"
